language: node_js
node_js:
  - "node"
script: gulp sass
deploy:
  provider: surge
  project: ./public/
  domain: freedomvote_master.surge.sh
  on: master
  skip_cleanup: true
notifications:
  slack: freedomvote:gNeosPsBstvqAz4z2U8UVA0Y
